Reorganize scripts
JetBrains-Research/Kotlin-Analysis pull request #14
Opened 2021-07-05 11:24 UTC by annav1asova

2021-07-05 11:42 UTC, nbirillo commented
@areyde Please, check English in this PR

2021-07-05 11:42 UTC, nbirillo approved these changes
Great! Thank you a lot!

2021-07-06 08:42 UTC, areyde requested changes
💯

2021-07-06 08:42 UTC, areyde commented on kotlin-analysis-clones/README.md
>  Run script for cleaning all duplicated repositories with different names:
the script

2021-07-06 08:42 UTC, areyde commented on kotlin-analysis-clones/README.md
>     You can use ```--save-metadata``` flag to download metadata about all projects. Metadata includes information about repository's full name, owner, etc.
the ... flag

2021-07-06 08:42 UTC, areyde commented on kotlin-analysis-clones/README.md
>     You can use ```--save-metadata``` flag to download metadata about all projects. Metadata includes information about repository's full name, owner, etc.
the information

2021-07-06 08:42 UTC, areyde commented on kotlin-analysis-clones/README.md
>  You can use ```--batch-size n``` option (default value is 300).
the ... option

2021-07-06 08:42 UTC, areyde commented on scripts/README.md
> +Module contains scripts for collecting repositories from GitHub, running Intellij Idea Plugin on them and analyzing the results.
The module

2021-07-06 08:42 UTC, areyde commented on scripts/README.md
> +Module contains scripts for collecting repositories from GitHub, running Intellij Idea Plugin on them and analyzing the results.
comma before `and`

2021-07-06 08:42 UTC, areyde commented on scripts/analysis/clones/README.md
> +(converted from list of edges to adjacency list).
the list of edges to the adjacency list

2021-07-06 08:42 UTC, areyde commented on scripts/analysis/clones/README.md
> +Set correct paths to dataset, extracted methods and clones in the cell:
the dataset
comma before `and`

2021-07-06 08:42 UTC, areyde commented on scripts/analysis/clones/README.md
> +Notebook contains two parts: first is clones analysis based on the graph (it can be used without clones preprocessing),
The notebook

2021-07-06 08:42 UTC, areyde commented on scripts/analysis/clones/README.md
> +Notebook contains two parts: first is clones analysis based on the graph (it can be used without clones preprocessing),
first is the clones analysis

2021-07-06 08:42 UTC, areyde commented on scripts/analysis/clones/README.md
> +and second is based on the adjacency list (it can be used only after clones preprocessing,
the second

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +You can use [seart-ghs.si.usi.ch]( https://seart-ghs.si.usi.ch/) (main language: Kotlin) for this purpose.
I think this should be elaborated on, this is not understandable.

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +The file has to be in csv format with ```name``` column,
in the CSV format

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +The file has to be in csv format with ```name``` column,
the ... column

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +Run script for cleaning all duplicated repositories with different names:
the script

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +You can use ```--save-metadata``` flag to download metadata about all projects. Metadata includes information about repository's full name, owner, etc.
the ... flag, the metadata

2021-07-06 08:42 UTC, areyde commented on scripts/data_collection/README.md
> +Optional argument ```--allowed-extensions``` accepts a list of extensions.
The optional argument

2021-07-06 08:42 UTC, areyde commented on scripts/plugin_runner/README.md
> +Also, there is ```--start-from n``` option to start from batch with given number.
the ... option

2021-07-06 08:42 UTC, areyde commented on scripts/plugin_runner/README.md
> +Also, there is ```--start-from n``` option to start from batch with given number.
a given number

2021-07-06 08:42 UTC, areyde commented on scripts/plugin_runner/README.md
> +This process runs IntelliJ Idea plugin and may get stack for some reason.
stuck :)

2021-07-06 08:42 UTC, areyde commented on scripts/plugin_runner/README.md
> +If so, kill the process and rerun it with ```--start-from n``` option (using number of the last processed batch).
the ... option

2021-07-08 09:33 UTC, merged