Ranges analyzer
JetBrains-Research/Kotlin-Analysis pull request #22
Opened 2021-07-21 12:38 UTC by annav1asova

2021-07-22 08:56 UTC, nbirillo requested changes
Great, thank you!

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-core/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/AnalysisExecutor.kt
> +                    println("Opening project $projectPath (index ${i++})")
Why do not you use `forEachIndexed`?

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-core/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/Resource.kt
> +        }
header?.let{ writer.println(header) }. But probably you should send header into getPrintWriter function with default value null?

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-core/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/util/Utils.kt
> +fun getRelativePathToKtElement(ktElement: KtElement): Path {
Maybe this function is more applicable for PSI util? And I prefer extension function...Do you?

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/README.md
> +gradle :kotlin-analysis-plugin:cli -Prunner="kotlin-ranges-analysis" -Pinput="/path/to/dataset/dir" -Poutput="path/to/results/dir"
Please, delete quotes from this example, it is incorrect

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/BinaryExpressionRangesFqPsiAnalyzer.kt
> +        val expressionFqName = psiElement.resolveToCall()?.resultingDescriptor?.fqNameOrNull().toString()
Maybe is it better to throw error() if we can not resolve this call? it means we did not open the project correctly

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/BinaryExpressionRangesPsiAnalyzer.kt
> +        }
I am not sure that this case is applicable for when statement... Maybe should we use just if? since you have very different when branches

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/CallExpressionRangesFqPsiAnalyzer.kt
> +        val methodFqName = psiElement.resolveToCall()?.resultingDescriptor?.fqNameOrNull().toString()
Should we throw error() if the project does not resolve all dependencies?

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/CallExpressionRangesFqPsiAnalyzer.kt
> +        println(psiElement.text + (" ".repeat(40 - psiElement.text.length)) + methodFqName)
What is it?))

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/RangesAnalysisExecutor.kt
> +    private fun saveOtherContextStats(
Please add a comment that describes these arguments

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/RangesContextAnalyzer.kt
> +                    return ContextType.FOR
Maybe you can add a property with KtElementType to ContextType enum?

2021-07-22 08:56 UTC, nbirillo commented on kotlin-analysis-statistic/src/test/kotlin/org/jetbrains/research/ml/kotlinAnalysis/RangesAnalysisExecutorTest.kt
> +        }
Can we use subtests?

2021-07-22 08:56 UTC, nbirillo commented on scripts/plugin_runner/merge_data.py
> +
Please, add some description into this file

2021-07-22 13:50 UTC, annav1asova commented on kotlin-analysis-statistic/src/main/kotlin/org/jetbrains/research/ml/kotlinAnalysis/CallExpressionRangesFqPsiAnalyzer.kt
> +        println(psiElement.text + (" ".repeat(40 - psiElement.text.length)) + methodFqName)
Oops

2021-07-23 07:27 UTC, tiginamaria approved these changes
Great, thank you! I'm a bit late and have nothing to comment on! Maybe you can place collected statistics in any beautiful format to README.md to save and share it somewhere)

2021-07-23 09:58 UTC, nbirillo approved these changes
Great! I agree with @tiginamaria. If you add some examples it would be great

2021-07-23 13:34 UTC, merged