Python dependency analysis
JetBrains-Research/Kotlin-Analysis pull request #40
Opened 2021-09-24 15:14 UTC by GirZ0n

2021-09-27 09:38 UTC, nbirillo requested changes
Thank you a lot for the many tests! @annav1asova Could you please review this PR too?

2021-09-27 09:38 UTC, nbirillo commented on python-analysis-dependencies/src/main/kotlin/org/jetbrains/research/ml/pythonAnalysis/FromImportStatementPsiAnalyzer.kt
> +            0 -> {
Could you please add some const for this number?

2021-09-27 09:38 UTC, nbirillo commented on python-analysis-dependencies/src/main/kotlin/org/jetbrains/research/ml/pythonAnalysis/FromImportStatementPsiAnalyzer.kt
> +                when (psiElement.isStarImport) {
Maybe here is it better to use if operator?

2021-09-27 09:38 UTC, nbirillo commented on python-analysis-dependencies/src/main/kotlin/org/jetbrains/research/ml/pythonAnalysis/FromImportStatementPsiAnalyzer.kt
> +                when (psiElement.isStarImport) {
And here too

2021-09-28 08:37 UTC, nbirillo approved these changes
Great! Thank you!

2021-09-28 08:37 UTC, merged

2021-09-28 12:56 UTC, annav1asova reviewed
Sorry for being late, but everything looks great, thank you!